import fs from 'fs'

const data = JSON.parse(fs.readFileSync('src/data/cards.json', 'utf-8'))

const deepDives = {
  3: {
    summary: "The Second Law of Thermodynamics states that the total entropy of an isolated system always increases over time. Entropy is a measure of disorder — the number of ways a system can be arranged. A scrambled egg has higher entropy than an intact one because its molecules are more disordered. There are vastly more disordered arrangements than ordered ones, so disorder naturally increases. This is why time has direction: the universe moves from low entropy (order) to high entropy (disorder). Eventually, the universe will reach 'heat death' — maximum entropy where no work is possible. Everything will be the same temperature, particles evenly spread, no stars burning, no life. But this is trillions of years away. For now, the arrow of time keeps moving forward because entropy keeps increasing, and you cannot unscramble an egg.",
    bullets: ["Entropy = disorder; it always increases in an isolated system", "The arrow of time exists because the universe moves from order to disorder", "Heat death is the eventual maximum-entropy end state of the universe"]
  },
  7: {
    summary: "Photosynthesis is the process by which plants, algae, and some bacteria convert sunlight into chemical energy. It happens in chloroplasts inside plant cells. Chlorophyll, the green pigment, absorbs photons from sunlight. The energy from those photons excites electrons, which get passed along a chain of proteins (the electron transport chain). This splits water molecules (H₂O) into oxygen (O₂), protons (H⁺), and electrons (e⁻). The electrons reduce CO₂ into glucose (C₆H₁₂O₆) — storing the sun's energy in chemical bonds. The overall reaction: 6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂. Every oxygen molecule you breathe was split from water by sunlight in a plant. Photosynthesis powers almost all life on Earth — directly (plants) or indirectly (everything that eats plants). Without it, there'd be no oxygen, no food, no fossil fuels. It is the most fundamental energy conversion system on the planet.",
    bullets: ["Plants split water using sunlight to grab electrons for making sugar", "The oxygen you breathe comes from water molecules split by photosynthesis", "Almost all life on Earth depends on this process directly or indirectly"]
  },
  11: {
    summary: "Quantum tunneling is a phenomenon where a particle passes through a barrier it classically shouldn't be able to cross. In classical physics, a ball cannot roll through a wall — it doesn't have enough energy. But at the quantum scale, particles behave like waves. A particle's wavefunction describes the probability of finding it at any location. Even when the wavefunction encounters a barrier, a tiny portion of it 'leaks through' to the other side. That means there's a small-but-nonzero probability the particle is on the other side of the barrier. This isn't hypothetical — it happens constantly. The transistors in your computer's processor rely on quantum tunneling (electrons tunneling through thin insulating layers). The Sun's nuclear fusion depends on protons tunneling through the electrostatic repulsion barrier — otherwise the Sun couldn't fuse hydrogen and would be dark. Scanning Tunneling Microscopes (STM) use tunneling current to image individual atoms. It's weird, it's counterintuitive, and it's essential for reality as we know it.",
    bullets: ["Particles have a wavefunction — a small part can 'leak' through barriers", "Your computer's transistors and the Sun's fusion both depend on tunneling", "Scanning Tunneling Microscopes use it to image individual atoms"]
  },
  15: {
    summary: "The observable universe is the portion of the universe we can see from Earth — about 93 billion light-years across. Why 93 billion if the universe is only 13.8 billion years old? Because the universe is expanding. Light from the most distant galaxies has been traveling for 13.8 billion years, but during that time space itself has stretched, so the galaxies that emitted that light are now much farther away. We cannot see beyond the observable horizon — the light from there hasn't had time to reach us yet. The universe contains at least 100 billion galaxies, each with 100-400 billion stars. That's roughly 10²² stars. The observable universe is only a tiny fraction of the whole universe — which could be infinite. And it's expanding at an accelerating rate, driven by dark energy (68% of the universe). Dark matter (27%) holds galaxies together. Ordinary matter — everything we can see, touch, and measure — makes up only 5%.",
    bullets: ["The observable universe is 93 billion light-years across, not 13.8 billion", "Space expands, so distant galaxies are now much farther than when their light left", "Ordinary matter is only 5% — dark matter 27%, dark energy 68%"]
  },
  19: {
    summary: "Your brain is not a hard drive — it's more like a gardener that prunes connections to make the garden healthier. Forgetting isn't a failure; it's a critical feature. Your brain forms about 7 million new neural connections per second during childhood. Obviously it can't keep all of them. So it prunes unused connections (synaptic pruning) to optimize for what matters. Sleep is when the magic happens. During deep sleep, your brain replays the day's experiences, strengthening important memories and weakening irrelevant ones. At the same time, the glymphatic system — your brain's waste-cleaning mechanism — flushes out metabolic debris like beta-amyloid (the protein linked to Alzheimer's). This is why pulling all-nighters backfires so badly: you're preventing both memory consolidation AND toxin clearance. Matthew Walker's research shows that getting less than 6 hours of sleep increases Alzheimer's risk by 33%. Your brain needs sleep the way your body needs water.",
    bullets: ["Forgetting is a feature, not a bug — your brain prunes unused connections", "Sleep consolidates memories and flushes out brain toxins (like Alzheimer's-linked proteins)", "Pulling all-nighters prevents BOTH memory formation AND brain cleansing"]
  },
  23: {
    summary: "Natural selection is the mechanism behind evolution — the process by which species change over generations. It's not a force, but a filter. Here's how it works: 1) Variation — individuals in a population have different traits (due to genetic mutations). 2) Inheritance — many of these traits are heritable. 3) Differential survival — traits that improve survival and reproduction become more common in the next generation. Over millions of years, these small advantages compound. A slight variation in beak shape makes a finch better at cracking seeds. That finch lives longer, has more offspring, and passes on the beak trait. Eventually, that population becomes a different species. Evolution doesn't have a goal — there's no 'better' or 'worse,' only 'fits the current environment.' The bacteria that survive antibiotics aren't 'smarter' — they just happened to have a mutation that made them resistant. The survivors reproduce, and soon the whole population is resistant. That's natural selection in fast-forward.",
    bullets: ["Natural selection = variation + inheritance + differential survival", "Evolution has no goal — only 'fits the current environment' matters", "Antibiotic resistance is natural selection happening in real-time"]
  },
  27: {
    summary: "The Fibonacci sequence (0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55…) is a number sequence where each number is the sum of the two before it. What makes it remarkable is how frequently it appears in nature. Sunflower seed spirals follow Fibonacci numbers: the number of clockwise and counterclockwise spirals are consecutive Fibonacci numbers (typically 34 and 55, or 55 and 89). Pinecones, pineapples, artichokes, and cauliflower all show Fibonacci spirals. Nautilus shells approximate the golden spiral — a logarithmic spiral derived from the Fibonacci ratio (each new section is ~1.618 times bigger than the last). This isn't magic — it's efficient packing. Fibonacci spirals allow seeds and petals to be packed with maximum density in a given space. The golden ratio (Φ ≈ 1.618) also appears in galaxy arms, hurricanes, and even the proportions of the human hand. The universe seems to prefer this pattern because it's the most space-efficient way to grow.",
    bullets: ["Fibonacci numbers appear in nature because they're the most efficient packing arrangement", "Sunflowers, pinecones, and nautilus shells all follow Fibonacci spirals", "The golden ratio (1.618) is just the Fibonacci ratio — not magic, but math"]
  },
  31: {
    summary: "The Miller-Urey experiment of 1953 was a landmark attempt to understand how life began. Stanley Miller and Harold Urey simulated early Earth's conditions: a flask of water (the ocean) heated to produce vapor, mixed with methane (CH₄), ammonia (NH₃), and hydrogen (H₂) — thought to be the early atmosphere. They passed electrical sparks (simulating lightning) through the mixture continuously for a week. When they analyzed the residue, they found that amino acids — the building blocks of proteins — had formed spontaneously. Out of the 20 amino acids used by life, 11 formed in the experiment. This was stunning: the complex molecules necessary for life could form from simple ingredients and a common energy source (lightning). Subsequent experiments have shown that amino acids, sugars, lipids (fats), and even nucleic acid bases (components of DNA) form readily under similar conditions. The building blocks of life are not rare — they're an inevitable chemical reaction given the right ingredients and energy.",
    bullets: ["Miller-Urey showed that amino acids form spontaneously from simple chemicals + lightning", "Life's building blocks are not rare — they're an inevitable chemical reaction", "Subsequent experiments produced sugars, lipids, and DNA components under similar conditions"]
  },
  35: {
    summary: "Machine learning is a subset of AI where computers learn patterns from data instead of following explicit programmed rules. Instead of telling a computer 'if pixel 1 is this color and pixel 2 is that, then it's a cat,' we show it a million pictures of cats and let it figure out the pattern on its own. Neural networks are the most powerful approach: layers of interconnected 'neurons' (mathematical functions) that process information. Each connection has a weight that gets adjusted during training. Training involves feeding the network examples, comparing its predictions to the correct answers, and adjusting the weights to reduce the error. This process repeats millions of times. A large language model like GPT-4 has been trained on trillions of words and has hundreds of billions of parameters (weights). It doesn't 'understand' language the way humans do — it's predicting which word is most likely to come next, based on patterns in its training data. Machine learning is statistics on an enormous scale, made possible by massive datasets and powerful GPUs.",
    bullets: ["ML learns patterns from data instead of following explicit rules", "Neural networks adjust millions of internal weights through repeated training", "LLMs like GPT don't 'understand' — they predict the most likely next word"]
  },
  39: {
    summary: "Earth's outer shell (the lithosphere) is broken into about 15-20 tectonic plates that float on the semi-molten asthenosphere below. Think of them like giant rafts on a slow-moving river. They move about 2-15 centimeters per year — roughly as fast as your fingernails grow. There are three types of plate boundaries: divergent (plates move apart — magma rises, creating new crust, like the Mid-Atlantic Ridge), convergent (plates collide — one slides under the other in subduction zones, creating mountains and volcanoes like the Himalayas and the Ring of Fire), and transform (plates slide past each other — friction builds and releases as earthquakes, like the San Andreas Fault). The Himalayas are still rising about 5mm per year because the Indian plate continues to push into the Eurasian plate. The entire Atlantic Ocean is growing wider by a few centimeters each year. Over millions of years, plate tectonics builds mountains, opens oceans, triggers volcanic eruptions, and drives the carbon cycle that regulates Earth's climate. Without plate tectonics, Earth might be a dead planet like Mars.",
    bullets: ["Earth's crust is 15-20 plates floating on molten rock, moving at fingernail-growth speed", "Plate boundaries create mountains (convergent), new crust (divergent), and earthquakes (transform)", "Without plate tectonics, Earth might be geologically dead like Mars"]
  },
  43: {
    summary: "Antibiotics and antivirals target fundamentally different enemies. Bacteria are living single-celled organisms. They have cell walls, a metabolism, and can reproduce independently. Antibiotics work by exploiting differences between bacterial cells and human cells — for instance, penicillin prevents bacteria from building their cell walls, which kills them but doesn't affect human cells (which don't have cell walls). Viruses are not alive. They're genetic material (DNA or RNA) wrapped in a protein coat. They can't reproduce, metabolize, or do anything on their own — they must hijack a living cell's machinery to replicate. That's why antibiotics don't work on viruses: there's nothing to 'attack' without harming your own cells. This is also why we get the common cold and flu repeatedly — viruses mutate quickly, changing their protein coat just enough that last year's immunity doesn't recognize them. Antiviral drugs work by interfering with specific steps of viral replication (like Tamiflu blocking the flu virus from leaving infected cells). But they're much harder to develop than antibiotics.",
    bullets: ["Bacteria are alive; viruses are just genetic material in a protein coat", "Antibiotics kill bacteria by attacking structures human cells don't have", "Viruses mutate fast — that's why the cold and flu come back every year"]
  },
  47: {
    summary: "Lucy, discovered in 1974 in Ethiopia's Afar region, is a 3.2-million-year-old fossil of Australopithecus afarensis — about 40% of a complete skeleton. She was a small female, about 1.1 meters tall (3'7\"), weighing around 29 kg (64 lbs). What made Lucy revolutionary was her combination of features: she walked upright (bipedal) but had a small brain (about the size of a grapefruit — 380-430 cc, similar to a modern chimpanzee). The shape of her pelvis and knee joint clearly showed she walked on two legs. Before Lucy, scientists assumed large brains came first and bipedalism followed. Lucy proved the opposite: our ancestors stood up before they got smart. Walking upright freed the hands, which allowed tool use, which drove brain evolution. Lucy's species lived in East Africa's woodland environment, not open savanna as previously thought. They were likely both tree climbers (for safety) and bipedal walkers (for foraging). Lucy essentially rewrote the human origin story — and she did it with just one knee joint, a pelvis, and a jawbone that happened to survive 3.2 million years.",
    bullets: ["Lucy showed that bipedalism (walking upright) evolved BEFORE big brains", "Standing up freed hands, which enabled tool use, which drove brain growth", "She was tiny — 3'7\" with a chimp-sized brain — but walked like us"]
  },
  53: {
    summary: "Einstein's special relativity (1905) revolutionized our understanding of space and time with one radical idea: the speed of light is constant for all observers, no matter how fast they're moving. All other motion is relative. The consequences are bizarre. Time dilation: the faster you move through space, the slower time passes for you relative to a stationary observer. If you travel at 99.999% of light speed for one year, you'd return to Earth to find that decades or centuries had passed. This isn't science fiction — GPS satellites prove it every day. They orbit at 14,000 km/h, experiencing slightly slower time due to their speed (special relativity) and slightly faster time due to weaker gravity (general relativity). Together, these effects cause GPS satellite clocks to drift about 38 microseconds per day faster than Earth clocks. Without correcting for relativity, GPS would be off by kilometers within a day. The famous equation E=mc² came from special relativity — it says mass and energy are the same thing, just in different forms. A tiny amount of mass contains an enormous amount of energy: that's how nuclear power works.",
    bullets: ["The speed of light is constant for all observers — everything else is relative", "GPS satellites must correct for relativity or they'd be off by kilometers daily", "E=mc² means a tiny mass contains enormous energy"]
  },
  57: {
    summary: "When a massive star (8-20 times the Sun's mass) runs out of fuel and collapses, its core compresses so violently that protons and electrons merge into neutrons. The result: a neutron star — an object about 20 km across (the size of a city) but containing 1.4-2.16 times the mass of the entire Sun. A teaspoon of neutron star material would weigh about a billion tons on Earth. Neutron stars rotate incredibly fast — from once per second to an astonishing 716 times per second (pulsars). They're like cosmic lighthouses: beams of radiation shoot from their magnetic poles, and as the star spins, the beams sweep across space. When one of those beams points at Earth, we see a regular pulse — that's why they're called pulsars. The first pulsar was discovered in 1967 and was nicknamed LGM-1 (Little Green Men) because the signal was so regular it seemed artificial. Neutron stars have the strongest magnetic fields in the universe — trillions of times stronger than Earth's. Some neutron stars (magnetars) have fields so powerful they can distort atoms into cigar shapes and cause starquakes that release more energy in a tenth of a second than the Sun releases in 100,000 years.",
    bullets: ["A neutron star packs a Sun's mass into a city-sized ball — a teaspoon weighs a billion tons", "Pulsars are neutron stars that spin and beam radiation like cosmic lighthouses", "Magnetars have magnetic fields so strong they warp atoms into cigars"]
  },
  61: {
    summary: "Mitochondria are the power plants of your cells — tiny organelles that convert the food you eat into ATP (adenosine triphosphate), the energy currency of life. You have hundreds to thousands of mitochondria in every cell (more in energy-hungry cells like muscles and neurons). They have their own DNA (mtDNA) — separate from the DNA in your cell's nucleus — and it's inherited exclusively from your mother. The endosymbiotic theory explains why: about 1.5 billion years ago, a free-living bacterium was engulfed by a larger cell. Instead of being digested, it formed a symbiotic relationship — the host provided protection, and the bacterium provided energy (ATP). Over eons, the bacterium became a permanent resident — the mitochondrion. This explains why mitochondria have their own double membrane (like bacteria), their own DNA (circular, like bacteria), and replicate independently within your cells. Without mitochondria, complex life couldn't exist — a single human cell needs about 10 million ATP molecules per second, and only mitochondria can produce that much. Without them, you'd be dead in seconds.",
    bullets: ["Mitochondria convert food into ATP — you need 10 million ATP molecules per second per cell", "They have their own DNA (from mom only) because they were once free-living bacteria", "The endosymbiotic theory: bacteria moved in 1.5 billion years ago and never left"]
  },
  65: {
    summary: "Neuroplasticity is your brain's ability to reorganize itself by forming new neural connections throughout life. For most of the 20th century, scientists believed the adult brain was fixed — once you reached adulthood, you were stuck with what you had. We now know that's completely wrong. Your brain rewires itself constantly based on what you do. London taxi drivers must memorize 25,000 streets and thousands of landmarks ('the Knowledge'). Brain scans show their hippocampus — the memory center — is physically larger than average. And the longer they've been driving, the bigger it gets. Stroke patients whose motor cortex was damaged can retrain other brain regions to take over movement functions. People who learn to juggle develop more gray matter in visual-motion areas within just three months. Even more remarkably, studies show that mental practice alone — just imagining playing piano — produces nearly the same brain changes as actually playing. This is why rehab for brain injuries works, why learning a new skill changes your brain, and why 'you can't teach an old dog new tricks' is demonstrably false. The brain is plastic throughout life.",
    bullets: ["Your brain physically rewires itself based on what you do — even in adulthood", "London taxi drivers have larger hippocampi from memorizing 25,000 streets", "Imagining practicing piano produces nearly the same brain changes as actually playing"]
  },
  69: {
    summary: "If you're of non-African descent, approximately 1-4% of your DNA comes from Neanderthals — our closest extinct relatives. Modern humans (Homo sapiens) left Africa around 60,000-70,000 years ago and encountered Neanderthals in Europe and Asia. We interbred. Those ancient trysts left a lasting genetic legacy. The Neanderthal genes in your genome affect: your immune system (improved resistance to local pathogens), your skin and hair (keratin production for thicker hair), your risk for depression (slight increase), blood clotting (stickier blood — more clotting, higher stroke risk), and even your circadian rhythm (some get morning-person genes from Neanderthals). Interestingly, most Neanderthal genes on the X chromosome and in testes-related genes were weeded out by evolution — suggesting hybrid males may have had reduced fertility. Different human populations have different amounts: East Asians have the most (about 2.3-2.6%), Europeans slightly less (about 2%), and Sub-Saharan Africans the least (about 0.3% — from back-migration of Europeans). A 2018 study found that Neanderthals also contributed up to 0.5% of the DNA in modern Africans, likely through ancient migrations back into Africa. The Neanderthal genome was fully sequenced in 2010, and we now know there was also interbreeding with another group — the Denisovans. If you're Melanesian or Australian Aboriginal, up to 5% of your DNA comes from Denisovans.",
    bullets: ["Non-Africans have about 2% Neanderthal DNA — from interbreeding 50,000 years ago", "Neanderthal genes affect immunity, skin, hair, sleep patterns, and disease risk", "Some populations also carry Denisovan DNA — up to 5% for Melanesians"]
  },
  73: {
    summary: "Graphene is a single layer of carbon atoms arranged in a hexagonal (honeycomb) lattice, one atom thick — the thinnest material ever discovered, and the strongest. It was first isolated in 2004 by Andre Geim and Konstantin Novoselov (who won the Nobel Prize in 2010) using surprisingly low-tech methods: scotch tape. They literally peeled layers off graphite until they got down to a single atom layer. Graphene is about 200 times stronger than steel while being virtually weightless. It conducts electricity better than copper (with the highest electron mobility of any known material at room temperature), conducts heat better than diamond, is flexible, transparent (97.3% light transmission), and almost completely impermeable (not even helium atoms can pass through). Potential applications: ultrafast transistors and flexible electronics, stronger and lighter aircraft materials, efficient water filters (perfect for desalination — only water molecules pass through), improved batteries and supercapacitors (charges in minutes, lasts longer), and even biomedical devices. The challenge is mass production — making defect-free graphene at scale remains expensive and difficult. But graphene research is one of the most active fields in materials science, with thousands of papers published annually.",
    bullets: ["Graphene is one atom thick, 200x stronger than steel, and conducts electricity better than copper", "It was discovered with scotch tape — literally peeling layers off graphite", "Potential uses: flexible electronics, desalination filters, super-batteries, and lightweight aircraft"]
  },
  77: {
    summary: "The greenhouse effect is Earth's natural temperature regulation system. Certain gases in the atmosphere — carbon dioxide (CO₂), methane (CH₄), water vapor (H₂O), and nitrous oxide (N₂O) — trap heat from the sun like a blanket. Sunlight passes through the atmosphere and warms Earth's surface. The surface radiates heat back as infrared radiation. Greenhouse gases absorb some of this infrared radiation and re-radiate it in all directions, including back to the surface. Without this effect, Earth's average temperature would be about -18°C (0°F) instead of the comfortable 15°C (59°F) we enjoy. The problem: humans have increased CO₂ by over 50% since the Industrial Revolution (from 280 ppm to over 420 ppm). CO₂ levels haven't been this high in 3 million years — before modern humans existed. More greenhouse gas = more trapped heat = global warming. And it's accelerating: 2023 was the hottest year on record, Arctic sea ice is declining by 13% per decade, sea levels have risen 21 cm since 1880, and extreme weather events (hurricanes, heatwaves, floods, droughts) are becoming more frequent and intense. The last time CO₂ was this high, sea levels were 5-25 meters higher than today.",
    bullets: ["The greenhouse effect is natural and necessary — without it Earth would be -18°C", "We've increased CO₂ by 50% in 200 years, causing the planet to warm rapidly", "CO₂ levels haven't been this high in 3 million years — before humans existed"]
  },
  81: {
    summary: "The Higgs boson is the particle that proves the existence of the Higgs field — an invisible energy field that permeates all of space. The Higgs field gives mass to fundamental particles like electrons and quarks. How? Imagine an empty room (empty space) filled with thick molasses (the Higgs field). A celebrity walks in (a massless particle) — they move through easily because everyone crowds around them, but they're slowed down. A regular person (a particle with some mass) moves more slowly because the molasses sticks to them. A marble (a particle with no mass) rolls through the molasses unaffected. The more a particle interacts with the Higgs field, the more mass it has. The Higgs boson is the particle that carries the Higgs force — like how a photon carries electromagnetism. It was predicted in 1964 by Peter Higgs and others, but it took 48 years to find it. The Large Hadron Collider (LHC) at CERN — the world's most powerful particle accelerator — smashed protons together at near-light speed, generating the energy needed to produce Higgs bosons. They announced the discovery on July 4, 2012, and Higgs won the Nobel Prize in 2013. Without the Higgs field, all particles would be massless and travel at the speed of light — atoms, molecules, stars, and life as we know them could not exist.",
    bullets: ["The Higgs field gives mass to particles — interact more with it = more mass", "At CERN discovered it in 2012 using the LHC, the world's most powerful particle accelerator", "Without the Higgs field, everything would be massless and fly apart at light speed"]
  },
  85: {
    summary: "Your microbiome is the community of trillions of microorganisms — bacteria, viruses, fungi, and archaea — that live in and on your body. You have about 30 trillion human cells and about 39 trillion bacterial cells — you are more microbe than human (by count, though bacteria are much smaller). The vast majority live in your gut (the gut microbiome). These microbes are not passengers — they're essential partners. They digest food your body can't (fiber → short-chain fatty acids), produce vitamins (B12, K, folate, biotin), train your immune system (70% of your immune cells are in your gut), regulate inflammation, produce neurotransmitters (about 90% of your serotonin — the 'happiness molecule' — is made in your gut by bacteria), and even influence your mood and behavior through the gut-brain axis. The composition of your microbiome is affected by diet, antibiotics, stress, sleep, and exercise. A diverse microbiome is a healthy microbiome — and the modern Western diet (high processed food, low fiber) is reducing microbiome diversity. Some studies suggest that fecal microbiome transplants (FMT) — transferring stool from a healthy donor — can treat C. difficile infections with a 90% success rate, far better than antibiotics. Your gut bacteria are literally a second brain, and taking care of them (fiber, fermented foods, less antibiotics) is taking care of yourself.",
    bullets: ["You have more bacterial cells than human cells — you're a walking ecosystem", "90% of your serotonin is produced in your gut, not your brain", "Fecal transplants cure C. difficile 90% of the time — far better than antibiotics"]
  },
}

let updated = 0
for (const card of data) {
  if (deepDives[card.id]) {
    card.summary = deepDives[card.id].summary
    card.bullets = deepDives[card.id].bullets
    updated++
  }
}

fs.writeFileSync('src/data/cards.json', JSON.stringify(data, null, 2), 'utf-8')
console.log('Deep-dived', updated, 'science cards')
